/* The native side of the runtime API (spec §4.2), used by G2.
 *
 * `c2mix_input` reads one test vector; `c2mix_cut` and `c2mix_done` dump every
 * registered object. Both use the line format of §4.2: one JSON object per line,
 * keys are registered names, values are integer arrays, and a dump carries "tag"
 * and "k" as well.
 *
 * The parser is deliberately tiny — it only has to read what c2mix itself writes.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "c2mix.h"

#define C2MIX_MAX_OBJECTS 64

struct c2mix_obj {
  const char *name;
  unsigned char *p;
  size_t count, elem_size;
  int is_signed;
};

static struct c2mix_obj c2mix_objs[C2MIX_MAX_OBJECTS];
static size_t c2mix_nobjs;
static char *c2mix_vector;
static FILE *c2mix_out;
static FILE *c2mix_in;
static int c2mix_cut_seen[256];

/* The harness (generated by c2mix) is a function, not a main: that lets one process
 * run every test vector G2 asks for instead of one process per vector. */
void c2mix_body(void);

static void c2mix_die(const char *what, const char *name) {
  fprintf(stderr, "c2mix_rt: %s (%s)\n", what, name ? name : "");
  exit(2);
}

static FILE *c2mix_output(void) {
  if (!c2mix_out) {
    const char *path = getenv("C2MIX_OUTPUT");
    c2mix_out = path ? fopen(path, "w") : stdout;
    if (!c2mix_out) c2mix_die("cannot open C2MIX_OUTPUT", NULL);
  }
  return c2mix_out;
}

static const char *c2mix_line(void) {
  if (!c2mix_vector) c2mix_die("no test vector is loaded", NULL);
  return c2mix_vector;
}

/* Read the next line of the vector file; 0 at end of file. */
static int c2mix_next_vector(void) {
  if (!c2mix_in) {
    const char *path = getenv("C2MIX_INPUT");
    c2mix_in = path ? fopen(path, "r") : stdin;
    if (!c2mix_in) c2mix_die("cannot open C2MIX_INPUT", path);
  }
  size_t cap = 4096, len = 0;
  char *buf = malloc(cap);
  int ch;
  while ((ch = fgetc(c2mix_in)) != EOF && ch != '\n') {
    if (len + 1 >= cap) { cap *= 2; buf = realloc(buf, cap); }
    buf[len++] = (char)ch;
  }
  buf[len] = '\0';
  if (ch == EOF && len == 0) { free(buf); return 0; }
  free(c2mix_vector);
  c2mix_vector = buf;
  return 1;
}

/* Find "name" as a key and return the text just after its colon. */
static const char *c2mix_find(const char *line, const char *name) {
  size_t n = strlen(name);
  for (const char *p = line; (p = strchr(p, '"')) != NULL; p++) {
    if (strncmp(p + 1, name, n) == 0 && p[1 + n] == '"') {
      const char *q = p + 2 + n;
      while (*q == ' ' || *q == ':') q++;
      return q;
    }
  }
  return NULL;
}

static void c2mix_store(struct c2mix_obj *o, size_t i, long long v) {
  unsigned char *cell = o->p + i * o->elem_size;
  unsigned long long bits = (unsigned long long)v;
  for (size_t b = 0; b < o->elem_size; b++)
    cell[b] = (unsigned char)((bits >> (8 * b)) & 0xFF); /* little endian, like x86-64 */
}

static long long c2mix_load(const struct c2mix_obj *o, size_t i) {
  const unsigned char *cell = o->p + i * o->elem_size;
  unsigned long long bits = 0;
  for (size_t b = 0; b < o->elem_size; b++)
    bits |= (unsigned long long)cell[b] << (8 * b);
  if (o->is_signed && o->elem_size < 8 &&
      (bits >> (8 * o->elem_size - 1)) & 1)
    bits |= ~0ULL << (8 * o->elem_size);
  return (long long)bits;
}

static struct c2mix_obj *c2mix_lookup(const char *name) {
  for (size_t i = 0; i < c2mix_nobjs; i++)
    if (strcmp(c2mix_objs[i].name, name) == 0) return &c2mix_objs[i];
  return NULL;
}

void c2mix_register(const char *name, void *p, size_t count, size_t elem_size,
                    int is_signed) {
  if (c2mix_nobjs == C2MIX_MAX_OBJECTS) c2mix_die("too many objects", name);
  if (c2mix_lookup(name)) c2mix_die("registered twice", name);
  struct c2mix_obj *o = &c2mix_objs[c2mix_nobjs++];
  o->name = name;
  o->p = (unsigned char *)p;
  o->count = count;
  o->elem_size = elem_size;
  o->is_signed = is_signed;
}

void c2mix_input(const char *name) {
  struct c2mix_obj *o = c2mix_lookup(name);
  if (!o) c2mix_die("c2mix_input on an unregistered object", name);
  const char *q = c2mix_find(c2mix_line(), name);
  if (!q) c2mix_die("the test vector has no value for", name);
  if (*q == '[') q++;
  for (size_t i = 0; i < o->count; i++) {
    char *end;
    /* An unsigned 64-bit element can be above LLONG_MAX, so pick the reader by sign
     * rather than letting strtoll saturate. */
    long long v = (*q == '-') ? strtoll(q, &end, 10)
                              : (long long)strtoull(q, &end, 10);
    if (end == q) c2mix_die("short test vector for", name);
    c2mix_store(o, i, v);
    q = end;
    while (*q == ',' || *q == ' ') q++;
  }
}

static void c2mix_dump(const char *tag, int k) {
  FILE *fh = c2mix_output();
  fprintf(fh, "{\"tag\": \"%s\", \"k\": %d", tag, k);
  for (size_t i = 0; i < c2mix_nobjs; i++) {
    struct c2mix_obj *o = &c2mix_objs[i];
    fprintf(fh, ", \"%s\": [", o->name);
    for (size_t j = 0; j < o->count; j++) {
      long long v = c2mix_load(o, j);
      if (o->is_signed) fprintf(fh, "%s%lld", j ? ", " : "", v);
      else fprintf(fh, "%s%llu", j ? ", " : "", (unsigned long long)v);
    }
    fprintf(fh, "]");
  }
  fprintf(fh, "}\n");
  fflush(fh);
}

void c2mix_cut(int tag) {
  char name[32];
  int k = ++c2mix_cut_seen[tag & 0xFF];
  snprintf(name, sizeof name, "%d", tag);
  c2mix_dump(name, k);
}

void c2mix_done(void) {
  c2mix_dump("exit", 0);
}

int main(void) {
  while (c2mix_next_vector()) {
    c2mix_nobjs = 0;
    memset(c2mix_cut_seen, 0, sizeof c2mix_cut_seen);
    c2mix_body();
  }
  if (c2mix_out && c2mix_out != stdout) fclose(c2mix_out);
  return 0;
}
