"""Component H: the harness generator (spec §3, §4.2).

The harness is the only C file c2mix writes. It declares one local per registered
object, registers them, marks the symbolic ones, calls the entry function once and
ends with `c2mix_done()`. Both the executor and the native binary G2 compares against
run this same file, so the two always agree on what the objects are.

It is a function, `c2mix_body`, rather than a `main`: the native runtime supplies the
`main` that calls it once per test vector, so G2 can run a hundred thousand vectors in
one process. The executor simply starts at `c2mix_body` instead.

Everything it needs comes from the specification's `Target`: the argument names, their
C types and directions, and which argument (if any) receives the return value.
"""
from __future__ import annotations

from dataclasses import dataclass

from ..spec import dsl


@dataclass(frozen=True)
class Object:
    name: str
    ctype: str
    count: int
    direction: str          # in | out | inout
    signed: bool
    returned: bool = False  # receives the return value rather than being passed

    @property
    def is_array(self) -> bool:
        return self.count > 1 or self.ctype.endswith("[]")

    def declare(self) -> str:
        if self.is_array:
            return f"  {self.ctype} {self.name}[{self.count}] = {{0}};"
        return f"  {self.ctype} {self.name} = 0;"

    def address(self) -> str:
        return self.name if self.is_array else f"&{self.name}"

    def elem_size(self) -> str:
        return f"sizeof {self.name}[0]" if self.is_array else f"sizeof {self.name}"

    def argument(self) -> str:
        """How the object is written at the call site."""
        if self.is_array:
            return self.name
        return self.name if self.direction == "in" else f"&{self.name}"


def guess_signed(ctype: str) -> bool:
    """C type name -> how the specification reads its elements. `is_signed` is an
    interpretation, so a target may override it, but the name decides by default."""
    t = ctype.replace("const", "").strip()
    return not ("uint" in t or t.startswith("unsigned") or t in ("_Bool", "bool"))


def objects(target: dsl.Target, signed: dict[str, bool] | None = None) -> list[Object]:
    signed = signed or {}
    out = []
    for name, spec in target.args.items():
        kind = spec.kind
        ctype = kind.ctype if isinstance(kind, dsl.Array) else kind
        count = kind.count if isinstance(kind, dsl.Array) else 1
        out.append(Object(name, ctype, count, spec.direction,
                          signed.get(name, guess_signed(ctype)),
                          returned=(target.returns == name)))
    return out


def generate(target: dsl.Target, entry: str, objs: list[Object], *,
             includes: list[str] = (), declares: list[str] = (),
             defines: list[str] = ()) -> str:
    """The harness source. `includes` are quoted #includes (include mode), `declares`
    are prototypes (link mode), `defines` are target-supplied macros — all of them
    source text, never compiler flags: §5.3's flags stay fixed in the core."""
    passed = [o for o in objs if not o.returned]
    ret = next((o for o in objs if o.returned), None)
    call = f"{entry}({', '.join(o.argument() for o in passed)});"
    lines = [
        "/* generated by c2mix — do not edit */",
        "#include <stdint.h>",
        "#include <stddef.h>",
        '#include "c2mix.h"',
    ]
    lines += [f"#define {d}" for d in defines]
    lines += [f'#include "{i}"' for i in includes]
    lines += list(declares)
    lines += ["", "void c2mix_body(void);", "", "void c2mix_body(void) {"]
    lines += [o.declare() for o in objs]
    lines += [f'  c2mix_register("{o.name}", {o.address()}, {o.count}, '
              f'{o.elem_size()}, {int(o.signed)});' for o in objs]
    lines += [f'  c2mix_input("{o.name}");' for o in objs if o.direction in ("in", "inout")]
    lines.append(f"  {ret.name} = {call}" if ret else f"  {call}")
    lines += ["  c2mix_done();", "}", ""]
    return "\n".join(lines)
